Prototype
WildCodeSchool-2024-09/JS-Reims-p3-Yooliz pull request #35
Opened 2024-12-11 15:38 UTC by Jottiana

2024-12-12 11:09 UTC, Jessscript requested changes

2024-12-12 11:09 UTC, Jessscript commented on client/src/pages/Comparer/Comparer.tsx
> +  // const vehicules: Vehicule[] = [vehicule1];
Supprimer le code commenté

2024-12-12 11:09 UTC, Jessscript commented on client/src/pages/Compte/Compte.css
> +@media screen and (max-width: 768px) {
Pourquoi le max-widtth: 768px si nous sommes en mobile first. Je pense tu peux supprimer cette media query et par contre adapter la page en mode desktop.

2024-12-12 11:09 UTC, Jessscript commented on client/src/pages/Info/InfosEnviro.css
> +    padding: 40px 20px 20px 20px;
pas besoin de reprendre le padding sur la media query car il est identique dans la class "header" en mode mobile

2024-12-12 11:09 UTC, Jessscript commented on client/src/pages/Info/InfosEnviro.css
> +@media screen and (max-width: 768px) {
Pareil le max-width: 768px est nécessaire en mobile first ?

2024-12-12 11:09 UTC, Jessscript commented on client/src/pages/Info/InfosEnviro.css
> +@media screen and (max-width: 768px) {
Idem le max-width: 768px est nécessaire en mobile first ?

2024-12-13 10:03 UTC, paulcnl commented on client/src/pages/Compte/Compte.css
> +@media screen and (max-width: 768px) {
il y a des display none dedans donc je ne peux pas le retirer

2024-12-13 10:13 UTC, Jessscript commented on client/src/components/Footer/Footer.css
> +/* :root {
Code commenté ! Nein !

2024-12-13 10:13 UTC, Jessscript commented on client/src/components/Header/Header.css
> +/*bouton animation*/
supprimer ce petit commentaire svp

2024-12-13 10:13 UTC, Jessscript commented on client/src/components/Matricule.css
> +@media screen and (max-width: 768px) {
Pas de max width si on fonctionne en mobile first

2024-12-13 10:28 UTC, Jottiana commented on client/src/pages/Comparer/Comparer.tsx
> +  // const vehicules: Vehicule[] = [vehicule1];
Corrigé

2024-12-13 10:39 UTC, paulcnl commented on client/src/components/Matricule.css
> +@media screen and (max-width: 768px) {
tout est bon

2024-12-13 11:13 UTC, merged